name: publish to nuget

on:
  push:
    branches:
      - release

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Certificate
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'signingcert.cer'
          fileDir: '.'
          encodedString: ${{ secrets.SIGNING_CERT }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --no-build --configuration Release
      - name: Sign
        uses: DanaBear/code-sign-action@v4
        with:
          certificate: '${{ secrets.SIGNING_CERT }}'
          password: '${{ secrets.SIGNING_CERT_PASS }}'
          certificatesha1: '${{ secrets.SIGNING_CERT_HASH }}'
          certificatename: '${{ secrets.SIGNING_CERT_NAME }}'
          folder: '\a\Packages.StartWithOSSettings\Packages.StartWithOSSettings\bin\Release\'
          recursive: false
      - name: PushNuget
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
      - name: PushGithub
        # The github token is automatically being pulled from the workflow
        run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
